package com.example.demo.model;

import java.util.Date;

public class Booktable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktable.id
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktable.book_name
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktable.volume_num
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    private Integer volumeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktable.author_name
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    private String authorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booktable.published_date
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    private Date publishedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktable.id
     *
     * @return the value of booktable.id
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktable.id
     *
     * @param id the value for booktable.id
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktable.book_name
     *
     * @return the value of booktable.book_name
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktable.book_name
     *
     * @param bookName the value for booktable.book_name
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktable.volume_num
     *
     * @return the value of booktable.volume_num
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    public Integer getVolumeNum() {
        return volumeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktable.volume_num
     *
     * @param volumeNum the value for booktable.volume_num
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    public void setVolumeNum(Integer volumeNum) {
        this.volumeNum = volumeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktable.author_name
     *
     * @return the value of booktable.author_name
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktable.author_name
     *
     * @param authorName the value for booktable.author_name
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booktable.published_date
     *
     * @return the value of booktable.published_date
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    public Date getPublishedDate() {
        return publishedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booktable.published_date
     *
     * @param publishedDate the value for booktable.published_date
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    public void setPublishedDate(Date publishedDate) {
        this.publishedDate = publishedDate;
    }
}