package com.example.demo.mapper;

import com.example.demo.model.Booktable;
import com.example.demo.model.BooktableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BooktableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    long countByExample(BooktableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    int deleteByExample(BooktableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    int insert(Booktable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    int insertSelective(Booktable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    List<Booktable> selectByExample(BooktableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    Booktable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    int updateByExampleSelective(@Param("record") Booktable record, @Param("example") BooktableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    int updateByExample(@Param("record") Booktable record, @Param("example") BooktableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    int updateByPrimaryKeySelective(Booktable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booktable
     *
     * @mbg.generated Wed Mar 24 17:19:39 JST 2021
     */
    int updateByPrimaryKey(Booktable record);
}